-- Sample data for testing unified inbox

-- First, get or create a test LinkedIn account (you'll need to replace the user_id with your actual user_id)
-- For testing, you can run this after logging in:
-- SELECT id FROM auth.users LIMIT 1;

-- Insert sample conversations (replace 'YOUR_USER_ID' and 'YOUR_LINKEDIN_ACCOUNT_ID' with actual values)

-- Example:
-- INSERT INTO conversations (
--   linkedin_account_id,
--   participant_name,
--   participant_profile_url,
--   participant_headline,
--   participant_avatar_url,
--   last_message_at,
--   last_message_preview,
--   unread_count,
--   is_archived,
--   thread_id
-- ) VALUES
-- (
--   'your-linkedin-account-id-here',
--   'Sarah Johnson',
--   'https://linkedin.com/in/sarahjohnson',
--   'Product Manager at Tech Corp',
--   NULL,
--   NOW() - INTERVAL '2 hours',
--   'Thanks for connecting! I saw your profile and...',
--   2,
--   false,
--   'thread_001'
-- ),
-- (
--   'your-linkedin-account-id-here',
--   'Michael Chen',
--   'https://linkedin.com/in/michaelchen',
--   'Senior Developer at Startup Inc',
--   NULL,
--   NOW() - INTERVAL '1 day',
--   'Hey! Would love to discuss the opportunity...',
--   0,
--   false,
--   'thread_002'
-- ),
-- (
--   'your-linkedin-account-id-here',
--   'Emily Davis',
--   'https://linkedin.com/in/emilydavis',
--   'Recruiter at Fortune 500',
--   NULL,
--   NOW() - INTERVAL '3 days',
--   'I have an exciting opportunity that might...',
--   1,
--   false,
--   'thread_003'
-- );

-- Insert sample messages for each conversation
-- INSERT INTO messages (
--   conversation_id,
--   linkedin_account_id,
--   message_id,
--   sender_name,
--   sender_profile_url,
--   is_from_me,
--   content,
--   sent_at,
--   is_read
-- ) VALUES
-- -- Conversation 1 messages
-- (
--   (SELECT id FROM conversations WHERE thread_id = 'thread_001'),
--   'your-linkedin-account-id-here',
--   'msg_001_001',
--   'Sarah Johnson',
--   'https://linkedin.com/in/sarahjohnson',
--   false,
--   'Thanks for connecting! I saw your profile and I''m really impressed with your background.',
--   NOW() - INTERVAL '2 hours 30 minutes',
--   true
-- ),
-- (
--   (SELECT id FROM conversations WHERE thread_id = 'thread_001'),
--   'your-linkedin-account-id-here',
--   'msg_001_002',
--   'You',
--   NULL,
--   true,
--   'Thank you Sarah! I''d love to learn more about what you do.',
--   NOW() - INTERVAL '2 hours 15 minutes',
--   true
-- ),
-- (
--   (SELECT id FROM conversations WHERE thread_id = 'thread_001'),
--   'your-linkedin-account-id-here',
--   'msg_001_003',
--   'Sarah Johnson',
--   'https://linkedin.com/in/sarahjohnson',
--   false,
--   'I''m currently working on some exciting projects at Tech Corp. Would you be interested in a quick call next week?',
--   NOW() - INTERVAL '2 hours',
--   false
-- );

-- For quick testing, here's a query to check your data:
-- SELECT c.*, la.email 
-- FROM conversations c 
-- JOIN linkedin_accounts la ON c.linkedin_account_id = la.id 
-- ORDER BY c.last_message_at DESC;
